### ISSUE TITLE
Complete the Implementation for custom Stack and Queue classes

### ISSUE THREAD

**Issue by ca20110820** [ca20110820/MyProject#23]
## TODO
- [ ] Complete implementation for Stack
- [ ] Complete implementation for Queue
- [ ] Add more unit test methods for Stack
- [ ] Add more unit test methods for Queue
